language: php
dist: xenial

env:
  global:
    - GIT_NAME: "'Couscous auto deploy'"
    - GIT_EMAIL: phpactor@dantleech.com
    - GH_REF: github.com/phpactor/phpactor
    - secure: "VW6FdcejZkI5Qir/MqzTsDxGGmrPKr1CLrFZirkD9wHUehiaJr2Z8JixBQsZy7D1z9nEycdt6Yq4ZFqoI0mSUhElOO8AY96Wed4PjIIhJ3tJKta8Eoks0KtHT12qxaFmZvVAkqfzQ3RrtIexwTb2axS7/tQRE0ZhECGppUnCges/tjqTm0nRox96l4pdtTXXlWsjbLjyFhDdURZY0t5QXDKiNh0ctHswc3MrSCc9BcRsX5+zuz/E/0RAI+J0w2ghVWRj9eIeuhvf9zIiFZdA07B4V3TSdF0E2ftPli7YUyZA2KmQ/8MBOF3PBI48KhU+kt6iHFa1EDlqp4t2NqHaRUEtmaHhlv+0cXHmKF1xMKLbMQdnqTg/NeWa9p87wAJ4dnvF1k1I9T2c0opKM7D4hUDBkFsx62jlstVxjmv+STwdaAw8WDZUnyNOLczTrAEg7jzwroigd/mYF6/8hiNsol1PeQsVbJqsi/61y3T8WkjeqnJJYisRrXcgi09sJ64crnr4CW+PxBR/88ETp8mLeM3oBGn+Nh5FjOKPc9pAVoai6DgfeJZ3UATY+7i82Q5vRlG860axhLVqqt2nYMnjKDBwHnh6CNaPArT5hIQgq/9AmW30dhFXheHy8XKgJMiyUtgktBk2zx4YilwcZKtP2/Gb5DCTbdQPjLJAu9/h6w4="

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - composer install

script:
  - vendor/bin/phpunit
  # Run the benchmarks and send the results to the PHPBench reports server
  # (only if the secure key is present)
  - if [ -n "${REPORTS_API_KEY}" ]; then vendor/bin/phpbench run --store; else vendor/bin/phpbench run; fi;
  # Run the test suites for all the Phpactor packages
  - config/travis/testdeps
  - config/travis/testexts

jobs:
  include:
    - stage: test
      env: VIM
      php: 7.3
      before_script:
        - composer validate --strict
        # Install the PHP dependencies
        - composer install --optimize-autoloader --classmap-authoritative
        - bin/phpactor --version
        - sudo apt-get update -y
        - sudo apt-get install vim -fy
        # Install the VIM testing framework
        - git clone https://github.com/junegunn/vader.vim.git
      script:
        # Run the VIM Plugin tests
        - config/travis/vim-plugin-test.sh
    - php: 7.3
    - stage: docs
      php: 7.2
      if: branch = master
      before_script:
        - git config --global user.email "phpactor@dantleech.com"
        - git config --global user.name "Phpactor"
        - curl -OS http://couscous.io/couscous.phar
      script:
        - php couscous.phar travis-auto-deploy
